includedir /etc/krb5.conf.d/
includedir /var/lib/sss/pubconf/krb5.include.d/

[libdefaults]
  default_realm = {{ ipa_realm }}
  dns_lookup_realm = false
  dns_lookup_kdc = true
  rdns = false
  dns_canonicalize_hostname = false
  ticket_lifetime = 168h
  renew_lifetime = 360h
  forwardable = true
  udp_preference_limit = 0
  default_ccache_name = KEYRING:persistent:%{uid}

[realms]
  {{ ipa_realm }} = {
    pkinit_anchors = FILE:/var/lib/ipa-client/pki/kdc-ca-bundle.pem
    pkinit_pool = FILE:/var/lib/ipa-client/pki/ca-bundle.pem
    kdc = {{ ipa1_name }}
    kdc = {{ ipa2_name }}
    master_kdc = ipa1.ipa.t8.corp:88
    admin_server = ipa1.ipa.t8.corp:749
    default_domain = ipa.t8.corp
    kpasswd_server = ipa1.ipa.t8.corp:464
    auth_to_local = RULE:[1:$1@$0](^.*@{{ ad_realm }}$)s/@{{ ad_realm }}/@{{ ad_domain }}/
    auth_to_local = DEFAULT
  }

  {{ ad_realm }} = {
    kdc = {{ dc01_name }}
    kdc = {{ dc02_name }}
    default_domain = t8.corp
  }

[domain_realm]
  .{{ ipa_domain }} = {{ ipa_realm }}
  {{ ipa_domain }} = {{ ipa_realm }}
  .{{ ad_domain }} = {{ ad_realm }}
  {{ ad_domain }} = {{ ad_realm }}
  {{ inventory_hostname }} = {{ ipa_realm }}
