---
- name: Меняю имя ОС
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Устанавливаю freeipa-client
  ansible.builtin.apt:
    name:
      - freeipa-client
    force: true
    state: present

- name: Замена 127.0.1.1 в hostname
  replace:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\b.*'
    replace: '127.0.1.1       {{ inventory_hostname }}'
    backup: yes

- name: Добавляем контроллеры ipa и dc в hosts
  lineinfile:
    path: "/etc/hosts"
    line: "{{ item }}"
  loop:
      - "{{ ipa1_ip }} {{ ipa1_name }}"
      - "{{ ipa2_ip }} {{ ipa2_name }}"
      - "{{ dc01_ip }} {{ dc01_name }}"
      - "{{ dc02_ip }} {{ dc02_name }}"

- name: Проверка переменных из vault
  debug:
    msg: "Пароль: {{ ipa_admin_pass }}"

- name: Проверяю, находится ли ПК в домене
  ansible.builtin.shell: "grep -sc {{ ipa_realm }} /etc/ipa/default.conf; exit 0"
  register: domain_check
  changed_when: false

- name: Ввожу ПК в домен
  ansible.builtin.shell:
    cmd: ipa-client-install --principal=admin --password='{{ lookup('vars', 'ipa_admin_pass') }}' --mkhomedir --ssh-trust-dns --enable-dns-updates --no-ntp --domain={{ ipa_domain }} --server={{ ipa1_name }} --unattended
    executable: /bin/bash
  register: ipa_install_result
  async: 3600
  when: '"1" not in domain_check.stdout'

- name: Создаю конфиг sssd.conf
  ansible.builtin.template:
    src: templates/sssd.conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: '0600'

- name: Создаю конфиг krb5.conf
  ansible.builtin.template:
    src: templates/krb5.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'

- name: Создаю конфиг nsswitch.conf
  ansible.builtin.template:
    src: templates/nsswitch.conf
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: '0644'

- name: Останавливаем службу sssd
  ansible.builtin.service:
    name: sssd
    state: stopped

- name: Чистим кэш sssd
  ansible.builtin.command:
    cmd: rm -rf /var/lib/sss/db/*

- name: Выполнить перезагрузку если нужно
  block:
    - name: Перезагружаю ПК
      ansible.builtin.reboot:
        msg: "Перезагрузка по запросу Ansible"
      
    - name: Ожидаю восстановления соединения
      ansible.builtin.wait_for_connection:
        delay: 15
        timeout: 600
  when: reboot | default(false) | bool