---
# Делать перезагрузку во время введения в домен
reboot: yes

# Доменное имя ip адрес ipa серверов
ipa1_ip: 192.168.8.185
ipa2_ip: 192.168.8.186
ipa1_name: "ipa1.ipa.t8.corp"
ipa2_name: "ipa2.ipa.t8.corp"
ipa_realm: "IPA.T8.CORP"
ipa_domain: "ipa.t8.corp"

# Доменное имя и ip адрес AD серверов
dc01_ip: "192.168.8.32"
dc02_ip: "192.168.8.20"
dc01_name: "ad.t8.corp"
dc02_name: "adhard.t8.corp"
ad_realm: "T8.CORP"
ad_domain: "t8.corp"